name: Create Branch event
on: [ create ]
jobs:
  merge-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: yarn
        working-directory: ./Shared/GitHub/action-create-sync-commit
      - uses: ./Shared/GitHub/action-create-sync-commit
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"