name: Sleep for Azure DevOps reporting delay
on: [ push ]
jobs:
  sleep:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for 2 minutes
        uses: jakejarvis/wait-action@master
        with:
          time: '2m'