trigger:
  batch: true
  branches:
    include:
      - '*'
  paths:
    include: []
pr:
  autoCancel: true
  branches:
    include:
      - master
      - develop
  paths:
    include: []

stages:
  - stage: TERRAGRUNT
    displayName: 'Package Terraform'
    jobs: []
