parameters:
  hasSwagger: false
  name: ''
  projectName: ''
  projectRoot: ''
  regionName: ''
  variablesFileName: 'non-prod-vars.yml'

jobs:
  - job: ${{parameters.name}}
    variables:
      - template: '../../../AzurePipelines/CI/${{parameters.variablesFileName}}'
    pool:
      vmImage: ${{variables.vmImage}}
    steps:
      - template: ../Tools/dotnet-steps.yml
      - template: ./csharp-aws-sam-steps.yml
        parameters:
          awsCredentials: ${{variables.awsCredentials}}
          productCode: ${{variables.productCode}}
          projectName: ${{parameters.projectName}}
          projectRoot: ${{parameters.projectRoot}}
          regionName: ${{parameters.regionName}}
      - ${{ if eq(parameters.hasSwagger, true) }}:
          - template: ../Tools/node-steps.yml
      - ${{ if eq(parameters.hasSwagger, true) }}:
          - template: ./csharp-swagger.steps.yml
            parameters:
              projectRoot: ${{parameters.projectRoot}}
      - publish: $(Build.ArtifactStagingDirectory)
        artifact: ${{parameters.projectName}}