parameters:
  projectRoot: ''

steps:
  - script: |
      yarn
    workingDirectory: '$(Build.SourcesDirectory)/Shared/Scripts/Terragrunt'
    displayName: 'yarn install'

  - script: |
      dotnet build /p:CopyLocalLockFileAssemblies=true --configuration=Release
    workingDirectory: ${{parameters.projectRoot}}
    displayName: 'build with assemblies'

  - script: |
      PROJECT_NAME=$(echo "${{parameters.projectRoot}}" | cut -d '/' -f1  | tr '[:upper:]' '[:lower:]')
      echo "This is the project name: $PROJECT_NAME"

      PROJECT_DIR=$(echo "${{parameters.projectRoot}}" | cut -d '/' -f2)
      echo "This is the project dir number: $PROJECT_DIR"

      npx nswag aspnetcore2openapi /assembly:$PROJECT_DIR.dll /documentName:$PROJECT_NAME/v1 /output:swagger.json
    workingDirectory: ${{parameters.projectRoot}}/bin/Release/netcoreapp2.1
    env:
      ASPNETCORE_ENVIRONMENT: Development
    displayName: 'generate swagger.json'

  - script: |
      cp swagger.json $(Build.ArtifactStagingDirectory)
    workingDirectory: ${{parameters.projectRoot}}/bin/Release/netcoreapp2.1
    displayName: 'copy swagger.json to artifact'