parameters:
  directoryName: ''
  displayName: ''
  environment: ''
  name: ''
  projectName: ''
  regionName: ''
  stage: ''
  terragruntRoot: ''
  variablesFileName: 'non-prod-vars.yml'

jobs:
  - job: ${{parameters.name}}
    displayName: ${{parameters.displayName}}
    variables:
      - template: '../../../AzurePipelines/CI/${{parameters.variablesFileName}}'
    steps:
      - template: ../Tools/node-steps.yml
      - template: ./artifact-directory-steps.yml
        parameters:
          directoryName: ${{parameters.directoryName}}
          environment: ${{parameters.environment}}
          projectName: ${{parameters.projectName}}
          stage: ${{parameters.stage}}
          terragruntRoot: ${{parameters.terragruntRoot}}
      - template: ./terragrunt-steps.yml
        parameters:
          artifactName: ${{parameters.name}}
          awsCredentials: ${{variables.awsCredentials}}
          productCode: ${{variables.productCode}}
          regionName: ${{parameters.regionName}}
          terragruntRoot: ${{parameters.terragruntRoot}}
          terragruntDependencies: ${{variables.terragruntDependencies}}