parameters:
  name: ''
  terragruntRoot: ''
  regionName: ''
  variablesFileName: 'non-prod-vars.yml'

jobs:
  - job: ${{parameters.name}}
    variables:
      - template: '../../../AzurePipelines/CI/${{parameters.variablesFileName}}'
    steps:
      - template: ../Tools/node-steps.yml
      - template: ./terragrunt-steps.yml
        parameters:
          artifactName: ${{parameters.name}}
          awsCredentials: ${{variables.awsCredentials}}
          productCode: ${{variables.productCode}}
          regionName: ${{parameters.regionName}}
          terragruntRoot: ${{parameters.terragruntRoot}}
          terragruntDependencies: ${{variables.terragruntDependencies}}